### PR TITLE
Replace feathericons with phosphor icons

### PR DESCRIPTION
**Pull request by wilrona**
This pull request adds the new icons from the phosphor-react package replacing the react-feather package.
Here are some screenshots of the feature:
Capture d’écran 2023-02-01 à 08 37 01

### CODE REVIEW

**Comment by jpye-finch** [comment]
@rikukissa @wilrona 
We only need the bold variant

**Comment by jpye-finch** [comment]
apart from that. Looks great!

**Review by jpye-finch — APPROVED** [review]
Looks good to me!

**Comment by naftis** [comment]
@rikukissa @wilrona we're cleaning up PR's with Tameem; reminder to fix the tests to get this merged.

**Pull request merged**
