### PR TITLE
fix: update returned bundle of unassigned handler

### PR DESCRIPTION
**Pull request by Nil20**
https://github.com/opencrvs/opencrvs-core/blob/develop/packages/gateway/src/features/registration/root-resolvers.ts#L619

We only return the task id for an unassigned declaration.

### CODE REVIEW

**Comment by naftis** [comment]
nice catch, would it be safer though here: https://github.com/opencrvs/opencrvs-core/blob/develop/packages/gateway/src/features/registration/root-resolvers.ts?rgh-link-date=2024-05-28T13%3A38%3A46Z#L619

 to not assume the [0] is a Task and rather use `getTaskFromSavedBundle`

**Review by naftis — CHANGES_REQUESTED** [review]
Question

**Comment by Nil20** [comment]
> getTaskFromSavedBundle

Would be a safer approach, I suppose.

**Review by Zangetsu101 — APPROVED** [review]

**Comment by naftis** [comment]
Do we need this one for 1.5.0?

**Comment by Zangetsu101** [comment]
I don't think we use the taskId returned from the mutation for anything so it shouldn't matter

**Pull request merged**
