### PR TITLE
Track custom field changes for correction

### PR DESCRIPTION
**Pull request by Nil20**

### CODE REVIEW

**Comment by Nil20** [comment]
I've kept the Burkina Faso's temporary patch as the current fix as well. I don't think we can do some fix which could be marginally better(Doesn't mean it won't be another patch) and doesn't break something else in the process. 
The PR's open for brainstorming ideas about it anyway.

**Comment by Zangetsu101** [comment]
Riku has created some dev tasks for this ticket here: https://github.com/opencrvs/opencrvs-core/issues/6810 so I'm closing this ticket for now. @Nil20 you can reopen it when you get back to it

**Comment by rikukissa** [comment]
@Zangetsu101 Tahmid and Markus will need this in Madagascar so we need to get it to 1.5.0 😬

**Review by Zangetsu101 — APPROVED** [review]

**Comment by Zangetsu101** [comment]
@Nil20 Let's update CHANGELOG please and then we can merge it in

**Pull request merged**
