### PR TITLE
Add organisation view to list locations & offices

### PR DESCRIPTION
**Pull request by wilrona**
This pull request adds a new view to the app's main menu called "Organizations". This view is displayed for all user roles except for field agents. The view lists all administrative areas so that the user can see all levels of locations down to the office level. Clicking on an office takes the user to the Team view and also clicking on an administrative area takes the user to the performance view. Here are some screenshots of the feature:

Navigation with the organisation menu
Capture d’écran 2023-01-23 à 10 26 39

Organisation page
Capture d’écran 2023-01-23 à 10 26 57

The view of organisations in the next level with display of pagination
Capture d’écran 2023-01-23 à 10 27 11

The office list view
Capture d’écran 2023-01-23 à 10 27 23

### CODE REVIEW

**Comment by rikukissa** [comment]
Previous review comments here: https://github.com/opencrvs/opencrvs-core/pull/4586

**Comment by rikukissa** [comment]
Notice that the country name shouldn't be clickable when you haven't yet clicked on any other location. The font size also seems smaller

image
image

**Comment by rikukissa** [comment]
Another one. Notice how in the original design there's only one space around the slash `placeA / placeB`:
image

image

**Comment by rikukissa** [comment]
The icon on the list items should always remain as the "Activity" icon as per the Figma design. Offices should be clickable which would take the user to the team page:

image

**Comment by rikukissa** [comment]
Mobile view also looks slightly different from designs
image
image

**Comment by rikukissa** [comment]
I noticed the spacings are a bit different from what they are in the design
image
image

**Review by rikukissa — APPROVED** [review]

**Comment by rikukissa** [comment]
@jpye-finch could you give this one more try and approve if everything is to your liking?

**Comment by jpye-finch** [comment]
- [ ] We need a smart way to set the row height in ListViewSimplified: 48px or 56px? (see grid-auto-rows: minmax(56px, auto))
- Set Icon button to small
- Replace Activity icon with <Icon color="currentColor" name="Activity" size="medium" />
- Investigate why Link hover underline is different thickness... setting to 'a' can help but not consistently

Ive pushed some slight updates to the Storybook

**Comment by jpye-finch** [comment]
image

can we change the file name to :
AdministrativeLevels.tsx

**Pull request merged**
