### PR TITLE
ocrvs-1814 Added language selection option in login

### PR DESCRIPTION
**Pull request by Zangetsu101**
- Language preference is saved in IndexedDB.
- Passing the selected language to client app is pending.

### CODE REVIEW

**Comment by jpye-finch** [comment]
@Zangetsu101 @euanmillar. I missed our pin lock page. Which has the logout button top right. https://www.figma.com/file/Eosd9SIfA3em0dlDMMd1gTPZ/1.-Login%2FOnboarding?node-id=1569%3A2926

Plus need to hide the select if 1 language. Show if multiple languages.

**Comment by Zangetsu101** [comment]
So the pin lock page is actually part of the client app so if we want to change that it should be a different ticket I think. What do you think @euanmillar?

**Review by euanmillar — APPROVED** [review]
Great work! @Zangetsu101

**Comment by euanmillar** [comment]
Great point about the PIN lock page.  We need to test that and make a new ticket with a new language

**Pull request merged**
