### PR TITLE
feat: export scopes via toolkit

### PR DESCRIPTION
**Pull request by Zangetsu101**
So that they can be used in countryconfig

### CODE REVIEW

**Comment by Zangetsu101** [comment]
It felt too complex to add anything new to the toolkit and I think it won't scale well. Would it be possible to just have "@opencrvs/commons" as a dependency and pick the things we want to expose from there?

**Comment by rikukissa** [comment]
Thanks! Can you elaborate on the scaling concern you have? For me the most important bit is we have a clearly separated "external API" that we maintain and guarantee backwards compatibility for and then our internal bits that can change at any time

**Comment by Zangetsu101** [comment]
If we look at the changes I needed to make to add another module here, quite a few configurations were required(e.g. we need to make node & typescript happy, then specific d.ts files need to be copied over). That got me thinking it would get more complex as keep adding modules here

**Comment by rikukissa** [comment]
I wonder if we can improve the process so including a new module wouldn't be anything else than adding an import?

**Comment by makelicious** [comment]
For reference if helps: https://github.com/opencrvs/opencrvs-core/pull/8213

**Review by rikukissa — APPROVED** [review]

**Pull request merged**
