### PR TITLE
chore: Cleaned up the national ID integration code

### PR DESCRIPTION
**Pull request by PathumN99**
#7909 

- Removed the national ID select option in integrations UI.
- Removed  the national ID scope in backend.
- Removed the relevant translations from the country-config. [[#313](https://github.com/opencrvs/opencrvs-countryconfig/pull/313)]
- Removed MOSIP systemType in GraphQL schemas.

### CODE REVIEW

**Review by naftis — COMMENTED** [review]
👍 Thanks, looks good.

https://github.com/opencrvs/opencrvs-core/blob/02b2eeed0b485b86c3477f81a94849cdb483d0a7/packages/client/src/tests/schema.graphql#L864

https://github.com/opencrvs/opencrvs-core/blob/de0776f138a7922b8bc63905cde30eee72ba99af/packages/gateway/src/features/systems/schema.graphql#L31

we could also remove it in these GraphQL schemas and then run frontend type generation:

```
cd packages/client
TOKEN="" yarn generate-gateway-types
```

https://is-my-opencrvs-up.netlify.app/
you can find the registrar's token in the left panel when you are running the app locally

**Comment by tahmidrahman-dsi** [comment]
@PathumN99 I think you might have to take care of these cases as well

https://github.com/opencrvs/opencrvs-core/blob/ocrvs-7909/packages/webhooks/src/features/event/service.ts#L59-L60
https://github.com/opencrvs/opencrvs-core/blob/ocrvs-7909/packages/webhooks/src/features/event/service.ts#L74-L75

**Review by tahmidrahman-dsi — CHANGES_REQUESTED** [review]
@PathumN99 Nice work! Please have a look at the comment I made about the webhooks handlers

**Review by tahmidrahman-dsi — APPROVED** [review]
Good one @PathumN99, thank you

**Comment by tahmidrahman-dsi** [comment]
@PathumN99 one small test case needs to be removed to pass unit tests for webhooks

https://github.com/opencrvs/opencrvs-core/blob/764d1b02833a90896ce81535f4a29eb0df865e3c/packages/webhooks/src/features/event/service.test.ts#L1607-L1611

Also after you remove this test case, please consider removing subsequent unused codes

**Review by tahmidrahman-dsi — APPROVED** [review]

**Comment by naftis** [comment]
@PathumN99 on approval / ready to merge label, you can merge the pull request to develop

**Pull request merged**
