### PR TITLE
feat(g2p): allow searching with childs identifier

### PR DESCRIPTION
**Pull request by naftis**
#5858 

Saves any identifier that the child Patient might have and allows searching with it.

### CODE REVIEW

**Review by Zangetsu101 — APPROVED** [review]

**Comment by naftis** [comment]
@Zangetsu101 Yeah, I tested with an flow where for example the NATIONAL_ID is being added here:
https://github.com/opencrvs/opencrvs-farajaland/blob/22eb3643f03a0338ba5c15ccddc17c0a2167b62c/src/api/event-registration/service.ts#L48

I have added additional dev task to update the way MOSIP handles the identifier addition, as it directly injects it to Hearth without going through workflow/gateway/etc: https://github.com/opencrvs/opencrvs-core/issues/5885

**Comment by euanmillar** [comment]
@jpye-finch I think we should combine this with a mandatory type of ID field in the form which allows passport and driving licence as an option

**Comment by jpye-finch** [comment]
by mandatory you mean they must have this question in their form configuration? such as child date of birth?

not all countries will require/have an ID number

**Comment by euanmillar** [comment]
@jpye-finch yes, an ID has to be mandatory in our Farajaland configuration and therefore when using G2PConnect interfaces.  If a country doesnt have an ID as a mandatory field then they cant use G2PConnect.  Sorry I dont think there is anything we need from you explicitly after all, I just wanted to let you know the dependency.  In Farajaland I think we just make National ID field a mandatory field and it should be OK.

**Review by rikukissa — APPROVED** [review]

**Pull request merged**
