### PR TITLE
Ocrvs 3328 Style & icon fixes

### PR DESCRIPTION
**Pull request by tahmidrahman-dsi**
image

image

### CODE REVIEW

**Comment by Zangetsu101** [comment]
image
We should add some top-padding here

**Comment by Zangetsu101** [comment]
image
And also some bottom-padding

**Comment by tahmidrahman-dsi** [comment]
> image We should add some top-padding here

Fix given in https://github.com/opencrvs/opencrvs-core/pull/3632/commits/5382f6bc9eafb169fac1e5dbab122cc8118e2b1b

image

**Comment by tahmidrahman-dsi** [comment]
> image And also some bottom-padding

Fix given in https://github.com/opencrvs/opencrvs-core/pull/3632/commits/5382f6bc9eafb169fac1e5dbab122cc8118e2b1b

image

**Pull request merged**
