### PR TITLE
[3733] Remove Requested correction option in performance tab

### PR DESCRIPTION
**Pull request by favour234**
Screenshot 2022-09-08 at 11 58 29

### CODE REVIEW

**Review by rikukissa — APPROVED** [review]

**Comment by Zangetsu101** [comment]
@favour234 Could you rebase your PR to use the `release-v1.1.0` as the base branch please?

**Comment by favour234** [comment]
Alright...

**Comment by favour234** [comment]
close

**Comment by Zangetsu101** [comment]
closed in favor of #3951

**Pull request closed without merging**
