### PR TITLE
feat(ci): ensure all PRs have a changelog change

### PR DESCRIPTION
**Pull request by rikukissa**

### CODE REVIEW

**Comment by rikukissa** [comment]
> What about when we don't actually need changelog updates?

I think it's enough if in those cases you just ignore it

**Comment by Zangetsu101** [comment]
> > What about when we don't actually need changelog updates?
> 
> I think it's enough if in those cases you just ignore it

But won't linting fail in those cases? i.e. it would stop the unit tests from running right?

**Comment by rikukissa** [comment]
Ah, no I don't think it fails the run but good question. At least in this PR it passes ok
The code doesn't seem to fail it either
https://github.com/mskelton/changelog-reminder-action/blob/main/src/runAction.ts#L7-L33

**Comment by Zangetsu101** [comment]
Okay so this only gives you reminder by commenting on your PR. That's fine then, but shouldn't there have been a reminder on this PR? :thinking:

**Comment by rikukissa** [comment]
There was but I removed it and now it's not adding it again :(

**Comment by rikukissa** [comment]
> Oops! Looks like you forgot to update the changelog.

lol

**Pull request merged**
