### PR TITLE
signature payload fix for marriage

### PR DESCRIPTION
**Pull request by Nil20**

### CODE REVIEW

**Comment by naftis** [comment]
image
Looks good to me.

**Comment by Zangetsu101** [comment]
@naftis @Nil20 Although the bug might be fixed, I'm afraid this would break some existing functionality. What I'm guessing is that if a fieldagent sends a marriage declaration with the signatures, a registrationagent validates that declaration(makes no changes to the signatures) & afterwards if a registrar downloads that declaration then the signatures would seem broken.

**Comment by Zangetsu101** [comment]
Okay I was wrong. It's even worse, the download of the declaration failed for the registrar :cold_sweat: 
Peek 2023-09-12 17-08

**Comment by naftis** [comment]
hmm, @Zangetsu101 I'll revert and re-open a pull request

**Pull request merged**
