### PR TITLE
ocrvs-1794 Sorting implemented in field agent details view

### PR DESCRIPTION
**Pull request by emon-swe-sust**
sort

All columns in field agent list and application workflow are made sortable, and the selected column by which rows are sorted are captioned bold on table header.

### CODE REVIEW

**Review by tahmidrahman-dsi — APPROVED** [review]
Awesome work!

**Comment by emon-swe-sust** [comment]
Thank you vai <3

**Comment by jpye-finch** [comment]
nice one! @emon-swe-sust  minor design update.
Can we only bold the heading text of the column that is sorted

**Comment by emon-swe-sust** [comment]
> nice one! @emon-swe-sust minor design update. Can we only bold the heading text of the column that is sorted

Columns that are sortable are bold, but there is arrow icon only on selected column by which rows are sortable. so if we bold the column that is sorted how can we distinguish the columns those are also sortable ?

**Comment by jpye-finch** [comment]
@emon-swe-sust I think all columns should be sortable. Type and Office for instance could still be sorted alphabetically. Sent incomplete, numerically

**Review by euanmillar — APPROVED** [review]

**Pull request merged**
