### PR TITLE
feat: log and mask the notification details

### PR DESCRIPTION
**Pull request by naftis**
#6418

Improves the logging when core sends a notification to country config. Implements masking functions to hide emails.

#### Masking

image
image

#### Logging
Email: `mother@mother.com`

image

### CODE REVIEW

**Comment by Zangetsu101** [comment]
We have a maskEmail function here in login: https://github.com/opencrvs/opencrvs-core/blob/develop/packages/login/src/utils/authUtils.ts#L44-L54

**Review by rikukissa — APPROVED** [review]

**Comment by rikukissa** [comment]
> @Zangetsu101 I might leave it as is to separate the PII filtering logging methods and the UI hiding of the email.
> 
> Why is the user-faced email hidden anyway in login if it comes from the user's input just previously 🤔

Isn't it because as part of login user supplies their username but not their email. In case it's someone trying to login with stolen credentials, they might not know which email address receives the 2FA

**Comment by naftis** [comment]
> > @Zangetsu101 I might leave it as is to separate the PII filtering logging methods and the UI hiding of the email.
> > Why is the user-faced email hidden anyway in login if it comes from the user's input just previously 🤔
> 
> Isn't it because as part of login user supplies their username but not their email. In case it's someone trying to login with stolen credentials, they might not know which email address receives the 2FA

It's being done client-side though so it's not secure if this is the case

**Comment by Zangetsu101** [comment]
Yes ideally the response from server should have been masked instead of doing it client-side

**Comment by naftis** [comment]
> Yes ideally the response from server should have been masked instead of doing it client-side

Let's make an ticket out of it. It's not a critical security issue but not something that should happen

**Comment by rikukissa** [comment]
Ok, I'll make a ticket of this. Besides that, I think this ticket if fine

**Comment by rikukissa** [comment]
https://github.com/opencrvs/opencrvs-core/issues/7238

**Pull request merged**
